feat: implement websocket consumers
Project-Stage-Academy/UA1244_beta pull request #107
Opened 2024-10-23 19:07 UTC by gogolmariana

Implemented
<img width="891" alt="Screenshot 2024-10-23 at 21 05 17" src="https://github.com/user-attachments/assets/ac3d3c9a-2fa6-4ea9-b077-0c815622d4eb">
 WebSocket consumers that handle sending and receiving messages in real-time.
<img width="897" alt="Screenshot 2024-10-23 at 21 04 51" src="https://github.com/user-attachments/assets/7f8958eb-7769-4dae-a74b-d8ac39a20472">
<img width="865" alt="Screenshot 2024-10-23 at 21 02 05" src="https://github.com/user-attachments/assets/ab241c09-cb9c-4e04-941d-c9a8a480c964">

2024-10-24 14:12 UTC, mehalyna requested changes

2024-10-26 21:57 UTC, gogolmariana commented on forum/communications/consumers.py
> +        )
Done!

2024-10-26 22:47 UTC, gogolmariana commented on forum/communications/views.py
> +            )
Rewrote the Consumer to an AsyncConsumer

2024-10-28 14:57 UTC, Chelakhovl approved these changes

2024-10-28 15:42 UTC, k0drin approved these changes

2024-10-28 20:28 UTC, merged