added method funding_received
Project-Stage-Academy/UA1244_beta pull request #108
Opened 2024-10-24 09:04 UTC by YuTumchuk

I added a method to the Project model that:

calculates the total funding of the project,
returns absolute values in monetary terms,
and relative values in percentages (this part is commented out but can be uncommented at any time).

2024-10-24 14:22 UTC, mehalyna requested changes

2024-10-24 14:22 UTC, mehalyna commented on forum/projects/models.py
> +            raise ValidationError(_('Actual finish date cannot be earlier than planned start date.'))
Move `clean()` method inside the `Project` class to ensure it's executed automatically when model instances are saved.

2024-10-24 14:22 UTC, mehalyna commented on forum/projects/models.py
Adding a `check` constraint ensures that `investment_share` values don’t exceed 100% across subscriptions. This complements the existing unique constraint.
```
class Meta:
    constraints = [
        models.UniqueConstraint(fields=['project', 'investor'], name='unique_project_investor'),
        models.CheckConstraint(
            check=models.Q(investment_share__gte=0, investment_share__lte=100),
            name='check_investment_share'
        ),
    ]
```

2024-10-24 14:22 UTC, mehalyna commented on forum/projects/models.py
> +    return self.title
Move `__str__()` to the `Project` as well.

2024-10-27 11:07 UTC, mehalyna approved these changes

2024-10-28 08:52 UTC, gogolmariana approved these changes

2024-10-28 14:28 UTC, AnnKvytko approved these changes

2024-10-28 20:45 UTC, merged