93-4 93-5 create a custom view for o auth login and user creation
Project-Stage-Academy/UA1244_beta pull request #111
Opened 2024-10-25 18:37 UTC by Chelakhovl

Created the OAuthTokenObtainPairView, a custom API view that handles the OAuth-based login process.
The view performs the following steps:
OAuth Authentication: Authenticates users using either Google or GitHub OAuth, retrieving the authorization code and exchanging it for an access token.
User Retrieval or Creation: If the user already exists in our system, they are retrieved; if not, a new user is created with the data provided by the OAuth provider.
JWT Token Assignment: Once the user is authenticated, the view assigns them a JWT token for secure access to our platform.
This was implemented by leveraging Django's RefreshToken.for_user() method, which issues the user a new JWT token upon successful OAuth login.
Code References:

OAuthTokenObtainPairView in views.py: Contains the logic for handling Google/GitHub OAuth login, checking for existing users, creating new users as necessary, and assigning JWT tokens.
Task 2: Create a Celery Task to Send a Welcome Email on Successful Registration or Login
Objective:
To configure a Celery task that sends a welcome email notification to the user upon successful registration or login.

Implementation:

Added a new Celery task, send_welcome_email, in tasks.py that sends a welcome email with the user's details.
The task is triggered asynchronously after successful registration or login by calling send_welcome_email.apply_async with the user’s ID as an argument.
Configured the email template to include the user's name and email, making the email more personalized and welcoming.
Set up the Celery task configuration in the settings and ensured that the Celery worker is connected to Redis, allowing for smooth background task processing.
Code References:

send_welcome_email in tasks.py: Contains the logic for sending the welcome email using Django’s send_mail function.
CustomSocialAccountAdapter in adapters.py: This adapter activates users after registration and triggers the send_welcome_email task.
The email configuration and template setup in settings.py ensure that the email is sent from the configured SMTP settings.
![1](https://github.com/user-attachments/assets/fd044332-9fc6-4b7f-ac42-332b57b8d708)
![2](https://github.com/user-attachments/assets/e3de314b-2f7f-43c9-afdf-58b43891bb86)
![3](https://github.com/user-attachments/assets/2c115b53-fe55-4e72-aa81-175d55000f79)

2024-10-26 09:09 UTC, mehalyna requested changes

2024-10-26 09:09 UTC, mehalyna commented on forum/users/adapter.py
> +        send_welcome_email.apply_async(args=[user_id])
Passing `user_id` as a string is unnecessary since the task can handle integers.

2024-10-26 09:09 UTC, mehalyna commented on forum/users/adapter.py
> +        user.save()
If the user saving or the task fails, there is no error handling.

2024-10-26 09:09 UTC, mehalyna commented on forum/users/tasks.py
> +        send_mail(subject, message, from_email, recipient_list, fail_silently=False)
You may use Django’s `render_to_string` for creating dynamic email content (like HTML templates), improving maintainability and user experience.

2024-10-26 09:09 UTC, mehalyna commented on forum/users/tasks.py
> +        user = User.objects.get(user_id=user_id)
Use `select_related()` to avoid multiple queries:
```
user = User.objects.select_related().get(user_id=user_id)
```

2024-10-27 08:02 UTC, mehalyna approved these changes

2024-10-27 08:59 UTC, gogolmariana approved these changes

2024-10-27 09:38 UTC, k0drin approved these changes

2024-10-27 09:38 UTC, merged