50 security and privacy measures 40 6
Project-Stage-Academy/UA1244_beta pull request #122
Opened 2024-11-03 19:17 UTC by gogolmariana

2024-11-04 09:08 UTC, mehalyna commented on forum/communications/consumers.py
> +        )
In `connect` and `disconnect`, it’s good practice to handle exceptions with user-specific details in logs to make debugging easier. Adding validation for `user_id` could avoid unexpected behavior. Confirm that `user_id` is an integer or string as expected.

2024-11-04 10:09 UTC, mehalyna requested changes

2024-11-04 10:09 UTC, mehalyna commented on forum/communications/signals.py
Add exception handling around the notification creation and channel group sending to catch and log errors without interrupting the save operation.

2024-11-08 13:23 UTC, Chelakhovl approved these changes

2024-11-08 13:24 UTC, mehalyna approved these changes

2024-11-09 12:11 UTC, merged