11 set up docker
Project-Stage-Academy/UA1244_beta pull request #66
Opened 2024-10-05 14:09 UTC by k0drin

2024-10-05 15:58 UTC, mehalyna requested changes

2024-10-05 15:58 UTC, mehalyna commented on Dockerfile
Few suggestions:
 - System dependencies: add the possibility to install system dependencies.
 - pip optimization: add `--no-cache-dir` to reduce image size.
 - `.dockerignore`: recommended adding a `.dockerignore` file to avoid unnecessary files in the image.
 - optional entry point and port exposure: in comments.

_Example_
```
FROM python:3.11.5-slim-bullseye

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies if needed (optional)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /code

# Install Python dependencies
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Optionally, expose the application port
# EXPOSE 8000

# Add an entry point if needed (like running the app or a script)
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
```

2024-10-05 15:58 UTC, mehalyna commented on docker-compose.yml
> +      - db
Use a wait script or the `wait-for-it.sh` or `wait-for-postgres.sh` script to ensure the database is ready before Django starts.
```
command: >
  ./wait-for-it.sh db:5432 -- python /code/forum/manage.py runserver 0.0.0.0:8000
```

2024-10-05 15:58 UTC, mehalyna commented on docker-compose.yml
> +      - db
Define environment variables like `DJANGO_SECRET_KEY`, `DJANGO_DEBUG`, etc., either in the `docker-compose.yml` file (for development only) or in a `.env` file for better separation of concerns.

2024-10-07 06:37 UTC, mehalyna approved these changes

2024-10-07 07:37 UTC, gogolmariana approved these changes

2024-10-07 08:07 UTC, Chelakhovl approved these changes

2024-10-07 09:25 UTC, merged