"Set Up JWT Authentication with Djoser and DRF SimpleJWT, User Model Enhancements, Serializers, API Views, and URL Configuration"
Project-Stage-Academy/UA1244_beta pull request #67
Opened 2024-10-06 17:29 UTC by Chelakhovl

In this pull request, we've accomplished the following:

    -  Set up JWT authentication using Djoser and Django Rest Framework SimpleJWT.
    -  Enhanced the User model to support additional fields such as roles and phone numbers.
    -  Created serializers for the User and Role models to properly handle registration and role assignment.
    -  Implemented API views for user registration, authentication, and retrieval.
    -  Configured URLs to integrate the new API views and enable secure token-based access.
    -  Also tested with the help of postman
These changes provide a secure and flexible registration and authentication flow while allowing users to have multiple roles (e.g., investor, startup).
![1](https://github.com/user-attachments/assets/1dd28ed2-433d-4188-ae6a-43f7dbcbb0db)
![2](https://github.com/user-attachments/assets/61f0d0b8-6837-468a-a28f-4b55152b4fd8)
![3](https://github.com/user-attachments/assets/45676f4c-3a06-430f-80ca-e9b7290a9990)

2024-10-07 15:20 UTC, mehalyna requested changes

2024-10-07 15:20 UTC, mehalyna commented on forum/users/serializers.py
> +        user.set_password(password)
`set_password` method already performs validation for password hashing, so there’s no need to repeat password setting logic inside the serializer.

2024-10-07 16:43 UTC, Chelakhovl commented
![1](https://github.com/user-attachments/assets/aaf40d52-6c0b-4879-8d27-2fcbc5ff4c80)
it works! Thank you for your advices!

2024-10-08 08:48 UTC, mehalyna approved these changes

2024-10-08 08:51 UTC, gogolmariana approved these changes

2024-10-08 08:55 UTC, k0drin approved these changes

2024-10-08 08:58 UTC, merged